DataJukebox_helpExpression:
  path: '/DataJukebox/Help/Expression'
  defaults: { _controller: 'DataJukeboxBundle\Controller\DataJukeboxHelpController::helpExpressionAction' }

DataJukebox_helpFilter:
  path: '/DataJukebox/Help/Filter'
  defaults: { _controller: 'DataJukeboxBundle\Controller\DataJukeboxHelpController::helpFilterAction' }
