# DataJukeboxBundle\Resources\config\services.yml
services:
  DataJukebox:
    class: 'DataJukeboxBundle\Service'
    arguments: ['@doctrine']
    public: true

  # FORM
  #   Symfony 3.x: Passing a form type instance to the FormFactory::create*() methods
  #   is not supported anymore. Pass the fully-qualified class name of the type instead.
  #    <-> https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md#form
  #   This custom form factory service will be used (and lazily instantiated) only from
  #   Symfony 3.x and above
  DataJukebox.form.factory:
    class: 'DataJukeboxBundle\Form\FormFactory'
    arguments: ['@form.registry']
    public: true

  # DataJukebox.doctrine.event_listener:
  #   class: DataJukeboxBundle\DoctrineEventListener
  #   arguments: ['@security.token_storage']
  #   tags:
  #     - { name: doctrine.event_listener, event: onFlush }

  DataJukebox.twig.extension:
    class: 'DataJukeboxBundle\TwigExtension'
    arguments: ['@twig']
    tags:
      - { name: 'twig.extension' }

  DataJukebox.controller.controller:
    class: 'DataJukeboxBundle\Controller\Controller'
    arguments: ['DataJukebox.form.factory']
    public: true
